"""Add summary and actionable_insights to News

Revision ID: 889a5a3aa0bb
Revises: b747e647a713
Create Date: 2026-06-06 13:27:22.099854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '889a5a3aa0bb'
down_revision: Union[str, Sequence[str], None] = 'b747e647a713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('actionable_insights', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'actionable_insights')
    op.drop_column('news', 'summary')
    # ### end Alembic commands ###
