"""Add assets to RiskProfile

Revision ID: 903299428d15
Revises: 889a5a3aa0bb
Create Date: 2026-06-06 13:29:44.995794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '903299428d15'
down_revision: Union[str, Sequence[str], None] = '889a5a3aa0bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_profiles', sa.Column('assets', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_profiles', 'assets')
    # ### end Alembic commands ###
