"""Add ioc_data and cve_ids to News

Revision ID: d40057a72b9d
Revises: 903299428d15
Create Date: 2026-06-06 13:50:15.130719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd40057a72b9d'
down_revision: Union[str, Sequence[str], None] = '903299428d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('ioc_data', sa.JSON(), nullable=True))
    op.add_column('news', sa.Column('cve_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'cve_ids')
    op.drop_column('news', 'ioc_data')
    # ### end Alembic commands ###
