from fpdf import FPDF
from datetime import datetime
import os
from typing import List
from app.models.news import News

class ReportService:
    def generate_security_report(self, news_list: List[News], user_email: str) -> str:
        """
        Generates a PDF security report from a list of news articles.
        Returns the path to the generated PDF.
        """
        pdf = FPDF()
        
        # Load Korean Font
        font_dir = os.path.join(os.path.dirname(__file__), "..", "assets", "fonts")
        regular_path = os.path.join(font_dir, "NanumGothic-Regular.ttf")
        bold_path = os.path.join(font_dir, "NanumGothic-Bold.ttf")
        
        if os.path.exists(regular_path):
            pdf.add_font("NanumGothic", "", regular_path)
            if os.path.exists(bold_path):
                pdf.add_font("NanumGothic", "B", bold_path)
            font_name = "NanumGothic"
        else:
            font_name = "Arial" # Fallback

        pdf.add_page()
        
        # Header
        pdf.set_font(font_name, "B", 24)
        pdf.set_text_color(59, 130, 246) # NewsEye Blue
        pdf.cell(0, 20, "NewsEye Security Report", ln=True, align="C")
        
        pdf.set_font(font_name, "", 12)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(0, 10, f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True, align="C")
        pdf.cell(0, 10, f"Prepared for: {user_email}", ln=True, align="C")
        pdf.ln(10)
        
        # Summary Section
        pdf.set_font(font_name, "B", 16)
        pdf.set_text_color(30, 41, 59)
        pdf.cell(0, 10, "Executive Summary", ln=True)
        pdf.set_font(font_name, "", 11)
        pdf.multi_cell(0, 8, f"본 보고서는 NewsEye 시스템이 탐지한 {len(news_list)}건의 고위험 보안 사고 분석 내용을 담고 있습니다. 귀하의 자산 및 일반 위험도를 기준으로 우선순위가 지정되었습니다.")
        pdf.ln(5)
        
        # Incident Details
        pdf.set_font(font_name, "B", 16)
        pdf.cell(0, 10, "Detailed Incident List", ln=True)
        pdf.ln(5)
        
        for idx, news in enumerate(news_list, 1):
            # Title
            pdf.set_font(font_name, "B", 12)
            pdf.set_text_color(30, 41, 59)
            pdf.multi_cell(0, 7, f"{idx}. {news.title}")
            
            # Metadata
            pdf.set_font(font_name, "", 9) # Using regular font for italic if not available
            pdf.set_text_color(100, 116, 139)
            pdf.cell(0, 5, f"출처: {news.source} | 위험도: {news.risk_level}/10 | 유형: {news.crime_type}", ln=True)
            
            # Summary
            pdf.set_font(font_name, "", 10)
            pdf.set_text_color(51, 65, 85)
            content = news.summary if news.summary else (news.content[:200] + "...")
            pdf.multi_cell(0, 6, content)
            
            # Insights
            if news.actionable_insights:
                pdf.set_font(font_name, "B", 9)
                pdf.set_text_color(21, 128, 61) # Green
                pdf.cell(0, 5, "Actionable Insights:", ln=True)
                pdf.set_font(font_name, "", 9)
                pdf.multi_cell(0, 5, news.actionable_insights)
                
            pdf.ln(10)
            
            if pdf.get_y() > 250: # Avoid page overflow for an item
                pdf.add_page()

        # Footer
        pdf.set_y(-15)
        pdf.set_font(font_name, "", 8)
        pdf.cell(0, 10, "Confidential - Generated by NewsEye Threat Intelligence System", align="C")

        # Save PDF
        report_dir = "reports"
        if not os.path.exists(report_dir):
            os.makedirs(report_dir)
            
        filename = f"Security_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        filepath = os.path.join(report_dir, filename)
        pdf.output(filepath)
        
        return filepath

report_service = ReportService()
